import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "/styles/Home.module.css";
import cookies from "next-cookies";
import UserItem from "../../components/Users/UserItem";
import { useState } from "react";
import AddUser from "../../components/Users/AddUser";
import { verifyJwt } from "../../utils/jwt";

const inter = Inter({ subsets: ["latin"] });

function ManageUsers({ users, user }) {
  const [allUsers, setAllUsers] = useState(users)
  
  async function handleDeleteUser(id) {
    const token = localStorage.getItem("token");
    const response = await fetch(`${process.env.NEXT_PUBLIC_APP_URL}/api/user/id/${id}`, {
      method: "DELETE",
      headers: {
        "Content-Type": "application/json",
        token: token,
      },
      // body: JSON.stringify({_id: id})
    });
    if (response.ok) {
      // If user is deleted successfully, refresh the user list
      const usersResponse = await fetch(`${process.env.NEXT_PUBLIC_APP_URL}/api/users`, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          token: token,
        },
      });
      let usersResponseJson = { data: {} };
      if (usersResponse.ok) {
        usersResponseJson = await usersResponse.json();
      }
      setAllUsers(usersResponseJson.data);
    }
  }

  async function handleAddUser(formData) {
    const token = localStorage.getItem("token");
    const response = await fetch("/api/users", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        token: token
      },
      body: JSON.stringify(formData),
    });
    if (response.ok) {
      // If user is deleted successfully, refresh the user list
      const usersResponse = await fetch(`${process.env.NEXT_PUBLIC_APP_URL}/api/users`, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          token: token,
        },
      });
      let usersResponseJson = { data: {} };
      if (usersResponse.ok) {
        usersResponseJson = await usersResponse.json();
      }
      setAllUsers(usersResponseJson.data);
    }
  }

  

  let listOfNoms = allUsers.map((value, index) => {
    return (
      <UserItem user = {value} key = {index}  handleDeleteUser={handleDeleteUser} />
    );
  });

  return (
    <>
    <Head>
      <title>Manager les Utilisateurs</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="min-h-full w-full flex flex-col p-20 bg-[url('/backgound.png')] bg-repeat font-PlayfairDisplay">
      {user.role == "Admin" && <h1 className="font-semibold font-AnticDidone text-3xl p-2 text-center md:text-left">Management de tous les Utilisateurs</h1>}
      <div className="flex flex-row flex-wrap justify-center">
        {user.role == "Admin" && <AddUser handleAddUser={handleAddUser} />}
        {user.role == "Admin" && <ul className="list-none flex-1 p-5 flex gap-5 items-center justify-center flex-wrap w-full h-max">{listOfNoms}</ul>}
      </div>
    </main>
  </>
  );
}

export async function getServerSideProps(context) {
  const token = cookies(context).token;
  const email = verifyJwt(token) != null ? verifyJwt(token).email : "nomail";

  const userResponse = await fetch(`${process.env.NEXT_PUBLIC_APP_URL}/api/user/email/${email}`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      token: token,
    },
  });
  const usersResponse = await fetch(`${process.env.NEXT_PUBLIC_APP_URL}/api/users`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      token: token,
    },
  });

  let userResponseJson = { data: {} };
  let usersResponseJson = { data: [] };

  if (userResponse.ok) {
    userResponseJson = await userResponse.json();
  }

  if (usersResponse.ok) {
    usersResponseJson = await usersResponse.json();
  }

  return {
    props: { users: usersResponseJson.data, user: userResponseJson.data }, // will be passed to the page component as props
  };
}

export default ManageUsers;
