import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "/styles/Home.module.css";
import PlanActionForm from "../../components/PlanAction/PlanActionForm";

const inter = Inter({ subsets: ["latin"] });

function PlanAction() {
  return (
    <>
      <Head>
        <title>Plan d&apos;action QVT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <PlanActionForm />
      </main>
    </>
  );
}

export default PlanAction;
