export const allQVTNames = [
  "Sécurité matérielle",
  "Sentiment sécurité",
  "Equité",
  "Clarté missions",
  "Soutien collègues",
  "Soutien hiérarchie",
  "Equilibre de vie",
  "Confort matériel",
  "Plaisir",
  "Intérêt",
  "Qualité relations",
  "Sentiment d'appartenance",
  "Place",
  "Reconnaissance",
  "Estime personnelle",
  "Estime professionnelle",
  "Apprentissage",
  "Autonomie",
  "Expression",
  "Authenticité",
  "Responsabilités",
  "Perspectives",
  "Sens",
  "Valeurs",
  "Utilité",
  "Compétences",
  "Réalisation de soi",
];
