import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "/styles/Home.module.css";
import { unauthenticate } from "../utils/auth";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

function Home() {
  const router = useRouter()
  const logout = () => {
    unauthenticate();
    router.push('/login')
  }

  const getusers =  async () => {
    const res = await fetch('/api/users', {
      method: 'GET',
      headers: { 'Content-Type': 'application/json', 'token': localStorage.getItem("token") },
    });
    if (res.ok) {
        const json = await res.json();
        console.log(json)
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
    <button onClick={logout}>Se Deconnecter</button>
    <button onClick={getusers}>Récupérer la liste des utilisateurs</button>
      </main>
    </>
  );
}

export default Home