import { useRouter } from "next/router";
import LoginForm from "../components/Login/LoginForm";
import { isAuthenticated } from "../utils/auth";
import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "/styles/Home.module.css";


export default function LoginPage() {
  const router = useRouter();
  const [loggedIn, setLoggedIn] = useState(true);
  const [email, setEmail] = useState("");
  const [errorMessage, setErrorMessage] = useState("");

  const resetMail = async (event) => {
    event.preventDefault();
    const res = await fetch("/api/auth/send_reset_mail", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ email }),
    });
    if (res.ok) {
      const json = await res.json();
      console.log(json.message);
      setErrorMessage(json.message);
    } else {
      const json = await res.json();
      setErrorMessage(json.message);
    }
  };

  useEffect(() => {
    // Redirect the user to the login page if they are not authenticated
    if (isAuthenticated()) {
      router.push("/");
    } else {
      setLoggedIn(false);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Connectez-vous</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {!loggedIn && (
          <div>
            <h1>Se Connecter</h1>
            <LoginForm />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <input
             className="border"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <button onClick={resetMail}>Mot de passe oublié ?</button>
            <br />
            {errorMessage && <p style={{ color: "red" }}>{errorMessage}</p>}
          </div>
        )}
      </main>
    </>
  );
}
