import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "/styles/Home.module.css";
import MultiStepForm from "../components/Form/MultiStepForm";

const inter = Inter({ subsets: ["latin"] });

function Diagnostic() {
  return (
    <>
      <Head>
        <title>Diagnostic QVT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen">
        <MultiStepForm />
      </main>
    </>
  );
}

export default Diagnostic;
